// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/campaign": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/login": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/dashboard" | "/campaign" | "/profile" | "/login";
  };
  "routes/_protected.dashboard.tsx": {
    id: "routes/_protected.dashboard";
    page: "/dashboard";
  };
  "routes/_protected.campaign.tsx": {
    id: "routes/_protected.campaign";
    page: "/campaign";
  };
  "routes/_protected.profile.tsx": {
    id: "routes/_protected.profile";
    page: "/profile";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_protected.dashboard": typeof import("./app/routes/_protected.dashboard.tsx");
  "routes/_protected.campaign": typeof import("./app/routes/_protected.campaign.tsx");
  "routes/_protected.profile": typeof import("./app/routes/_protected.profile.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
};